Upgrade ruby from 2.4 to 3.1
cyberark/conjur-authn-k8s-client pull request #508
Opened 2023-04-05 15:55 UTC by juniortaeza

2023-04-12 15:09 UTC, rpothier approved these changes
LGTM!

2023-04-12 15:13 UTC, rpothier requested changes
Please update the changelog, otherwise looks good.

2023-04-13 15:41 UTC, rpothier submitted a review, later dismissed
Thanks for adding this.
It should go in the 0.25.0 section

2023-04-13 15:44 UTC, juniortaeza commented
That should fix things, thank you for reviewing!

2023-04-18 13:31 UTC, szh commented
@juniortaeza looks like helm tests are failing in CI

2023-04-18 13:35 UTC, john-odonnell commented
@szh Helm tests are fixed [here](https://github.com/cyberark/conjur-authn-k8s-client/pull/511), but the build still fails on a CLI bug I'm investigating.

2023-04-19 18:39 UTC, szh commented
I just rebased to include the helm fixes from #511

2023-04-19 18:47 UTC, szh commented
Hmm, still failing

2023-04-19 20:14 UTC, john-odonnell commented on helm/common/utils.sh
> +    helm unittest .
@szh Because we're pinning the `helm-unittest` version, we need to keep the `--helm3` flag. I'll push a commit updating this.

2023-04-20 13:15 UTC, john-odonnell approved these changes

2023-04-20 13:17 UTC, merged